modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="superiorarmor"
version="1.0.0"
displayName="SuperiorArmor"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="EmeraldGltch, MCreator"

[[dependencies.superiorarmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




